[package]
name = "simulator"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
adventuregraph_core = { path = "../core", package = "core" }
anyhow = { workspace = true }
embedded-graphics-simulator = "0.7.0"
mousefood = { workspace = true }
