[package]
name = "adventuregraph"
version = "0.1.0"
authors = ["Rafael García <bladecoder@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.71"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = [
    "std",
    "embassy",
    "esp-idf-svc/native",
    "bladeink/stream-json-parser",
]

pcbv1 = []
display-st7735 = []
software-scroll = []

pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = [
    "esp-idf-svc/embassy-sync",
    "esp-idf-svc/critical-section",
    "esp-idf-svc/embassy-time-driver",
]

[dependencies]
log = { version = "0.4", default-features = false }
esp-idf-svc = { version = "0.48.1", default-features = false }
#critical-section = { version = "1.1.2", features = ["std"] }
#bladeink = { version = "1.0.3" }
bladeink = { git = "https://github.com/bladecoder/blade-ink-rs.git", branch = "json_read_stream" }
esp-idf-hal = { version = "0.43.1", default-features = false }
anyhow = "1"
embedded-graphics = "0.8.1"
mipidsi = "0.8.0"
display-interface-spi = "0.5.0"
display-interface = "0.5.0"
# esp-display-interface-spi-dma = { git = "https://github.com/georgik/esp-display-interface-spi-dma.git", branch = "feature/esp-hal-0.17" }
# static_cell = "2.1.0"
# esp-bsp = "0.2.0"

[build-dependencies]
embuild = "0.31.4"
