[workspace]
resolver = "2"
members = ["core", "esp", "simulator", "tui", "tools/board-config"]
default-members = ["core", "simulator", "tui", "tools/board-config"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bladecoder/adventuregraph"

[workspace.dependencies]
bladeink = { git = "https://github.com/bladecoder/blade-ink-rs.git", rev = "007e99cf649f34ced27744067f565bd359c7c466", default-features = false, features = ["binary-image"] }
ratatui = { version = "=0.30.0", default-features = false, features = ["portable-atomic"] }
mousefood = { version = "=0.5.2", default-features = false }
ratatui-widgets = { version = "=0.3.0", default-features = false }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[profile.dev.package.adventuregraph-esp]
opt-level = "z"
