[package]
name = "core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "adventuregraph_core"

[dependencies]
anyhow = { workspace = true }
bladeink = { workspace = true }
ratatui = { workspace = true, features = ["unstable-rendered-line-info"] }
tui-widget-list = { workspace = true }
